language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7
- 3.8
cache: pip
install: make install
script: make test
after_success:
- coveralls
matrix:
  fast_finish: true
  include:
  - name: lint
    python: '3.8'
    install: make install-tools
    script: make lint
  - name: format
    python: '3.8'
    install: make install-tools
    script: make format
